config/routes.rb
Rails.application.routes.draw do
  resources :aeronaves
  devise_for :users
  get 'pages/home'
  resources :alunos

    root 'pages#home'

end

app/models/aeronave.rb
class Aeronave < ActiveRecord::Base
end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/aeronaves_controller.rb
class AeronavesController < ApplicationController
  before_action :set_aeronave, only: [:show, :edit, :update, :destroy]

  # GET /aeronaves
  # GET /aeronaves.json
  def index
    @aeronaves = Aeronave.all
  end

  # GET /aeronaves/1
  # GET /aeronaves/1.json
  def show
  end

  # GET /aeronaves/new
  def new
    @aeronave = Aeronave.new
  end

  # GET /aeronaves/1/edit
  def edit
  end

  # POST /aeronaves
  # POST /aeronaves.json
  def create
    @aeronave = Aeronave.new(aeronave_params)

    respond_to do |format|
      if @aeronave.save
        format.html { redirect_to @aeronave, notice: 'Aeronave was successfully created.' }
        format.json { render :show, status: :created, location: @aeronave }
      else
        format.html { render :new }
        format.json { render json: @aeronave.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aeronaves/1
  # PATCH/PUT /aeronaves/1.json
  def update
    respond_to do |format|
      if @aeronave.update(aeronave_params)
        format.html { redirect_to @aeronave, notice: 'Aeronave was successfully updated.' }
        format.json { render :show, status: :ok, location: @aeronave }
      else
        format.html { render :edit }
        format.json { render json: @aeronave.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aeronaves/1
  # DELETE /aeronaves/1.json
  def destroy
    @aeronave.destroy
    respond_to do |format|
      format.html { redirect_to aeronaves_url, notice: 'Aeronave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aeronave
      @aeronave = Aeronave.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aeronave_params
      params.require(:aeronave).permit(:nome, :numero_tripulantes, :tamanho, :numero, :chassi, :quantidade_horas_voo, :quantidade_motor)
    end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :sobrenome, :cpf, :endereco, :profissao, :email, :cnh, :escolaridade, :instituicao, :curso)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/aeronaves_helper.rb
module AeronavesHelper
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/aeronaves/_form.html.erb
<%= simple_form_for(@aeronave) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :numero_tripulantes %>
    <%= f.input :tamanho %>
    <%= f.input :numero %>
    <%= f.input :chassi %>
    <%= f.input :quantidade_horas_voo %>
    <%= f.input :quantidade_motor %>
  </div>


  <div class="form-actions text-center"> 
    <%= f.button :submit %>
  </div>
<% end %>

app/views/aeronaves/edit.html.erb
<h1>EDITANDO AERONAVE</h1>

<%= render 'form' %>

<%= link_to 'MOSTRAR', @aeronave %> |
<%= link_to 'VOLTAR', aeronaves_path %>

app/views/aeronaves/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">LISTA DE AERONAVES </h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">NOME</th>
      <th scope="col">NUMERO DE TRRIPULANTES</th>
      <th scope="col">TAMANHO</th>
      <th scope="col">NUMERO</th>
      <th scope="col">CHASSI</th>
      <th scope="col">QUANTIDADE DE HORAS DE VOO</th>
      <th scope="col">QUANTIDADE DE MOTOR</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aeronaves.each do |aeronave| %>
      <tr>
       <th scope="row"></th>
        <td><%= aeronave.nome %></td>
        <td><%= aeronave.numero_tripulantes %></td>
        <td><%= aeronave.tamanho %></td>
        <td><%= aeronave.numero %></td>
        <td><%= aeronave.chassi %></td>
        <td><%= aeronave.quantidade_horas_voo %></td>
        <td><%= aeronave.quantidade_motor %></td>
        <td><%= link_to 'Show', aeronave %></td>
        <td><%= link_to 'Edit', edit_aeronave_path(aeronave) %></td>
        <td><%= link_to 'Destroy', aeronave, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <p class="text-center"> <%= link_to 'NOVA AERONAVE', new_aeronave_path, class: ' btn btn-primary btn-lg' %> </p>

app/views/aeronaves/new.html.erb
<h1 class="text-center">NOVA AERONAVE</h1>

<%= render 'form' %>

<p class="text-center"> <%= link_to 'VOLTAR', aeronaves_path %></p>

app/views/aeronaves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aeronave.nome %>
</p>

<p>
  <strong>Numero tripulantes:</strong>
  <%= @aeronave.numero_tripulantes %>
</p>

<p>
  <strong>Tamanho:</strong>
  <%= @aeronave.tamanho %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @aeronave.numero %>
</p>

<p>
  <strong>Chassi:</strong>
  <%= @aeronave.chassi %>
</p>

<p>
  <strong>Quantidade horas voo:</strong>
  <%= @aeronave.quantidade_horas_voo %>
</p>

<p>
  <strong>Quantidade motor:</strong>
  <%= @aeronave.quantidade_motor %>
</p>

<%= link_to 'EDITAR', edit_aeronave_path(@aeronave) %> |
<%= link_to 'BACK', aeronaves_path %>

app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sobrenome %><br>
    <%= f.text_field :sobrenome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :profissao %><br>
    <%= f.text_field :profissao %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cnh %><br>
    <%= f.text_field :cnh %>
  </div>
  <div class="field">
    <%= f.label :instituicao %><br>
    <%= f.text_field :instituicao %>
  </div>
  <div class="field">
    <%= f.label :curso %><br>
    <%= f.text_field :curso %>
  </div>
  <div class="actions text-center">
    <%= f.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>EDITANDO ALUNO</h1>

<%= render 'form' %>

<%= link_to 'MOSTRAR', @aluno %> |
<%= link_to 'VOLTAR', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">LISTA DE ALUNOS</h1>


<table class="table">
  <thead>
    <tr>
      <th scope="col">NOME</th>
      <th scope="col">SOBRENOME</th>
      <th scope="col">CPF</th>
      <th scope="col">ENDEREÇO</th>
      <th scope="col">PROFISSÃO</th>
      <th scope="col">E-MAIL</th>
      <th scope="col">CNH</th>
      <th scope="col">INSTITUIÇÃO</th>
      <th scope="col">CURSO</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
      <th scope="row"></th>
        <td><%= aluno.nome %></td>
        <td><%= aluno.sobrenome %></td>
        <td><%= aluno.cpf %></td>
        <td><%= aluno.endereco %></td>
        <td><%= aluno.profissao %></td>
        <td><%= aluno.email %></td>
        <td><%= aluno.cnh %></td>
        <td><%= aluno.instituicao %></td>
        <td><%= aluno.curso %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br> 
<p class="text-center"><%= link_to 'NOVO ALUNO', new_aluno_path, class: ' btn btn-primary btn-lg' %></p>

app/views/alunos/new.html.erb
<h1 class="text-center">NOVO ALUNO</h1>

<%= render 'form' %>

<p class="text-center"><%= link_to 'VOLTAR', alunos_path %></p>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @aluno.sobrenome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @aluno.cpf %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @aluno.endereco %>
</p>

<p>
  <strong>Profissao:</strong>
  <%= @aluno.profissao %>
</p>

<p>
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

<p>
  <strong>Cnh:</strong>
  <%= @aluno.cnh %>
</p>

<p>
  <strong>Instituicao:</strong>
  <%= @aluno.instituicao %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @aluno.curso %>
</p>

<%= link_to 'EDITAR', edit_aluno_path(@aluno) %> |
<%= link_to 'VOLTAR', alunos_path %>

app/views/layouts/_header.html.erb
<ul class="nav nav-tabs"
  <li role="presentation"> <%= link_to "HOME".html_safe, root_path, class: 'navbar-brand' %></li>

</ul>
    <% if current_user %>   
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" href="alunos#index">ALUNO</a>
     <a class="nav-link active" href="aeronaves#index">AERONAVE</a>
  </li>
  </ul>
   <% end %>  
   
        <ul class="nav navbar-nav navbar-right">
    <% if current_user %>  
       <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    
            <li><%= link_to 'Editar Conta', edit_user_registration_path %></li>
            <li><%= link_to 'Desconectar', destroy_user_session_path, method: :delete %></li>
        
        </ul>          
         </div>  
    <% else %>      
        <li><%= link_to 'ENTRAR', new_user_session_path %></li>          
    <% end %>
  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AEROCLUBE</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= render'layouts/header' %>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
   <h1 class="text-center">AEROCLUBE ASAS DE AGUIA </h1>
 	 <p class="text-center"> <%= link_to 'ENTRAR', new_user_registration_path, class: ' btn btn-primary btn-lg' %> </p> 
</div>